// front_end-frameworks/vue/src/App.vue
<script setup>
import Header from "./components/layout/Header.vue";
import Hero from "./components/sections/Hero.vue";
import About from "./components/sections/About.vue";
import Features from "./components/sections/Features.vue";
import Insights from "./components/sections/Insights.vue";
import Contact from "./components/sections/Contact.vue";
import Footer from "./components/layout/Footer.vue";
</script>

<template>
	<Header />
	<Hero />
	<About />
	<Features />
	<Insights />
	<Contact />
	<Footer />
</template>

// front_end-frameworks/svelte/svelte-project/src/App.svelte
<script>
	import Header from "./components/layout/Header.svelte";
	import Hero from "./components/sections/Hero.svelte";
	import About from "./components/sections/About.svelte";
	import Features from "./components/sections/Features.svelte";
	import Insights from "./components/sections/Insights.svelte";
	import Contact from "./components/sections/Contact.svelte";
	import Footer from "./components/layout/Footer.svelte";
</script>

<Header />
<Hero />
<About />
<Features />
<Insights />
<Contact />
<Footer />
