// front_end-frameworks/vue/src/components/ui/Brand.vue
<script setup>
import { Squirrel } from "lucide-vue-next";

defineProps({
	label: { type: String, default: "Agentic AI" },
	iconClass: { type: String, default: "w-7 h-7 text-green-600" },
	textClass: { type: String, default: "text-sm font-bold" },
});
</script>

<template>
	<Squirrel :class="iconClass" />
	<span :class="textClass">{{ label }}</span>
</template>

// front_end-frameworks/react/src/components/ui/Brand.jsx
import { Squirrel } from "lucide-react";

function Brand({ label = "Agentic AI", iconClassName = "w-7 h-7 text-green-600", textClassName = "text-sm font-bold" }) {
	return (
		<>
			<Squirrel className={iconClassName} />
			<span className={textClassName}>{label}</span>
		</>
	);
}

export default Brand;
