// front_end-frameworks/svelte/svelte-project/src/components/ui/SectionTitle.svelte
<script>
	let {
		as = "h2",
		class: className = "",
		highlight = "",
		highlightClass = "block text-violet-300",
		children,
	} = $props();
</script>

<svelte:element this={as} class={className}>
	{@render children?.()}
	{#if highlight}
		<span class={highlightClass}>{highlight}</span>
	{/if}
</svelte:element>

// front_end-frameworks/react/src/components/ui/SectionTitle.jsx
function SectionTitle({ as: Tag = "h2", className = "", highlight, highlightClassName = "block text-violet-300", children }) {
	return (
		<Tag className={className}>
			{children}
			{highlight && <span className={highlightClassName}>{highlight}</span>}
		</Tag>
	);
}

export default SectionTitle;
