// front_end-frameworks/svelte/svelte-project/src/components/ui/SectionTitle.svelte
<script>
	let {
		as = "h2",
		class: className = "",
		highlight = "",
		highlightClass = "block text-violet-300",
		children,
	} = $props();
</script>

<svelte:element this={as} class={className}>
	{@render children?.()}
	{#if highlight}
		<span class={highlightClass}>{highlight}</span>
	{/if}
</svelte:element>

// front_end-frameworks/vue/src/components/ui/SectionTitle.vue
<script setup>
defineProps({
	as: { type: String, default: "h2" },
	highlight: { type: String, default: "" },
	highlightClass: { type: String, default: "block text-violet-300" },
});
</script>

<template>
	<component :is="as">
		<slot />
		<span v-if="highlight" :class="highlightClass">{{ highlight }}</span>
	</component>
</template>
