// front_end-frameworks/svelte/svelte-project/src/components/cards/InsightCard.svelte
<script>
	let { category, title, description, image, index } = $props();
</script>

<article
	class="relative h-72 sm:h-80 overflow-hidden rounded-3xl border border-slate-800 {index === 0
		? 'col-span-2'
		: 'col-span-1'}"
>
	<img src={image} alt={title} class="absolute inset-0 h-full w-full object-cover" />
	<div class="absolute inset-0 bg-gradient-to-t from-black via-black/60 to-black/10"></div>
	<div class="relative z-10 flex h-full flex-col justify-end items-start gap-2 p-6 text-left">
		<span
			class="w-fit rounded-full border border-violet-500/30 bg-violet-500/20 px-3 py-1 text-xs text-violet-300"
		>
			{category}
		</span>
		<h3 class="text-lg font-bold text-slate-50">{title}</h3>
		<p class="text-sm text-slate-400">{description}</p>
	</div>
</article>

// front_end-frameworks/vue/src/components/cards/InsightCard.vue
<script setup>
defineProps({
	category: { type: String, required: true },
	title: { type: String, required: true },
	description: { type: String, required: true },
	image: { type: String, required: true },
	index: { type: Number, required: true },
});
</script>

<template>
	<article
		class="relative h-72 sm:h-80 overflow-hidden rounded-3xl border border-slate-800"
		:class="index === 0 ? 'col-span-2' : 'col-span-1'"
	>
		<img
			:src="image"
			:alt="title"
			class="absolute inset-0 h-full w-full object-cover"
		/>
		<div class="absolute inset-0 bg-gradient-to-t from-black via-black/60 to-black/10" />
		<div class="relative z-10 flex h-full flex-col justify-end items-start gap-2 p-6 text-left">
			<span class="w-fit rounded-full border border-violet-500/30 bg-violet-500/20 px-3 py-1 text-xs text-violet-300">
				{{ category }}
			</span>
			<h3 class="text-lg font-bold text-slate-50">{{ title }}</h3>
			<p class="text-sm text-slate-400">{{ description }}</p>
		</div>
	</article>
</template>
